const labels = {
    aborted: ['已取消', 'Cancelled'],
    account: ['账号', 'Account'],
    accounts: ['账号', 'Accounts'],
    accountViewScope: ['账号视图按实际调用统计', 'Account view measures actual calls'],
    active: ['进行中', 'Active'],
    activeHint: ['活动快照独立于已完成统计', 'Active snapshots are separate from completed statistics'],
    activity: ['活动请求', 'Active requests'],
    activityEndedUnknown: ['已离开活动列表，尚未找到终态记录', 'No longer active; final record unavailable'],
    all: ['全部', 'All'],
    anomalies: ['数据异常', 'Data anomaly'],
    apiKeys: ['API Key', 'API keys'],
    apiKeyUnknown: ['未知调用方', 'Unknown caller'],
    asOf: ['数据时间', 'Data as of'],
    attempt: ['调用', 'Call'],
    attempts: ['账号调用', 'Account calls'],
    attemptScopeHint: ['每行只属于一次账号调用', 'Each row belongs to one account call'],
    auto: ['自动', 'Auto'],
    businessAndTests: ['全部请求类型', 'All request origins'],
    cache: ['缓存', 'Cache'],
    cache_fallback: ['缓存失效，已回退完整请求', 'Cache rejected; full request fallback'],
    cache_miss: ['未匹配可用缓存', 'No usable cache matched'],
    cache_selected: ['已选用缓存', 'Cached resource selected'],
    cached: ['缓存输入', 'Cached input'],
    cacheExpiresAt: ['本地复用截止', 'Local reuse deadline'],
    cacheIncluded: ['缓存已包含在总输入中', 'Cache is included in total input'],
    cacheRateHint: [
        '缓存 Token ÷ 总输入 Token；仅计算两项都有数据的调用',
        'Cached tokens / total input tokens; calls reporting both values only',
    ],
    cacheState: ['缓存状态', 'Cache state'],
    cacheUpstreamExpiresAt: ['上游资源到期', 'Upstream resource expiry'],
    callId: ['调用 ID', 'Call ID'],
    callOrder: ['调用序号', 'Call order'],
    calls: ['调用数', 'Calls'],
    cancelCount: ['取消', 'Cancelled'],
    cancelUnknown: ['取消 / 未知', 'Cancelled / unknown'],
    category: ['请求分类', 'Request category'],
    chain: ['完整请求链路', 'Full request chain'],
    clear: ['清除', 'Clear'],
    client: ['客户端', 'Client'],
    columns: ['列设置', 'Columns'],
    compact: ['紧凑', 'Compact'],
    completed: ['已完成', 'Completed'],
    connected: ['已连接', 'Connected'],
    connectionStale: ['数据已暂停', 'Updates paused'],
    continued: ['续聊', 'Continued'],
    conversation: ['对话', 'Conversation'],
    conversationAssociation: ['对话关联', 'Conversation association'],
    conversationConfigChanged: [
        '请求配置变化，对话归属保留；缓存独立匹配',
        'Request configuration changed; conversation retained and cache matched separately',
    ],
    conversationUnmatched: ['未关联', 'Unlinked'],
    copied: ['已复制', 'Copied'],
    copy: ['复制', 'Copy'],
    copyFailed: ['复制失败', 'Copy failed'],
    countAnomaly: ['计数异常：缓存大于输入', 'Count anomaly: cache exceeds input'],
    coverage: ['回报覆盖', 'Reporting coverage'],
    current: ['当前状态', 'Current state'],
    currentCall: ['当前账号调用', 'Selected account call'],
    custom: ['自定义', 'Custom'],
    day: ['天', 'Day'],
    denominator: ['仅计算成功与失败', 'Success and failure only'],
    density: ['密度', 'Density'],
    details: ['详情', 'Details'],
    disconnected: ['连接异常', 'Connection error'],
    duration: ['耗时', 'Duration'],
    empty: ['没有匹配记录', 'No matching records'],
    emptyAttempts: ['未调用上游账号', 'No upstream account call'],
    error: ['失败', 'Failed'],
    errorDetail: ['错误详情', 'Error details'],
    export: ['导出全部', 'Export all'],
    exportFiltered: ['导出筛选结果', 'Export filtered'],
    failedRefresh: ['更新失败，保留上次数据', 'Update failed; showing last data'],
    failedTest: ['测试失败', 'Test failed'],
    failures: ['失败', 'Failures'],
    failuresOnly: ['只看失败', 'Failures only'],
    filter: ['筛选', 'Filter'],
    finished: ['结束', 'Finished'],
    first_seen: ['首次记录', 'First seen'],
    firstIdentity: [
        '本项目首次记录该对话，不代表客户端刚新建对话',
        'First seen by this proxy; the client conversation may already exist',
    ],
    firstSeen: ['首次记录', 'First seen'],
    frozen: ['已保留当前页面，新记录可手动加载', 'Page preserved; load new records manually'],
    generationPhase: ['阶段', 'Phase'],
    granularity: ['时间粒度', 'Granularity'],
    history: ['已完成记录', 'Finished records'],
    history_match: ['历史前缀匹配（推断）', 'History prefix matched (inferred)'],
    history_unmatched: ['历史未关联', 'History not linked'],
    historyIdentity: [
        '按完整请求历史匹配，为推断结果；缓存命中不代表同一对话',
        'Inferred from request history; a cache hit does not identify a conversation',
    ],
    historyIncomplete: ['历史字段不完整', 'Incomplete historical fields'],
    historyMatch: ['历史推断', 'History inference'],
    historyUnmatchedIdentity: [
        '请求携带历史，但没有关联到既有对话',
        'History was supplied but no existing conversation was linked',
    ],
    hit: ['命中', 'Hit'],
    hitRate: ['命中率', 'Hit rate'],
    hour: ['小时', 'Hour'],
    import: ['导入', 'Import'],
    in_progress: ['生成中', 'Generating'],
    input: ['总输入', 'Total input'],
    invalidFilters: ['请检查日期、状态码和耗时范围', 'Check dates, status code and duration range'],
    ip: ['来源 IP', 'Client IP'],
    keyModels: ['按模型展开', 'Models'],
    last7d: ['7 天', '7 days'],
    last24h: ['最近 24 小时', 'Last 24 hours'],
    last30d: ['30 天', '30 days'],
    lastTest: ['最近测试', 'Last test'],
    lastUsed: ['最近调用', 'Last call'],
    latest: ['最近使用', 'Last used'],
    loading: ['加载中…', 'Loading…'],
    loadNew: ['加载新记录', 'Load new records'],
    local: ['本地', 'Local'],
    localCache: ['本地缓存决策', 'Local cache decision'],
    localReject: ['本地拒绝', 'Local rejection'],
    logHint: ['在系统日志中搜索请求 ID', 'Search the request ID in system logs'],
    logs: ['系统日志', 'System logs'],
    manage: ['管理账号', 'Manage account'],
    maxDuration: ['最长耗时（毫秒）', 'Max duration (ms)'],
    minDuration: ['最短耗时（毫秒）', 'Min duration (ms)'],
    miss: ['未命中', 'Miss'],
    model: ['模型', 'Model'],
    models: ['模型', 'Models'],
    modelUsage: ['模型用量', 'Model usage'],
    more: ['更多筛选', 'More filters'],
    moreData: ['尚未采集', 'Not collected'],
    mostCalls: ['调用最多', 'Most calls'],
    neverTested: ['未测试', 'Not tested'],
    newRecords: ['条新记录', 'new records'],
    next: ['下一页', 'Next'],
    nonCached: ['非缓存输入', 'Uncached input'],
    note: ['说明', 'Note'],
    origin: ['请求类型', 'Request origin'],
    outcome: ['结果', 'Outcome'],
    output: ['输出', 'Output'],
    page: ['页', 'Page'],
    partial: ['已回报合计', 'Reported subtotal'],
    passedTest: ['测试通过', 'Test passed'],
    path: ['接口路径', 'Endpoint'],
    pause: ['暂停更新', 'Pause'],
    previous: ['上一页', 'Previous'],
    production: ['业务请求', 'Production'],
    protocol: ['协议', 'Protocol'],
    queued: ['排队中', 'Queued'],
    raw: ['原始 usageMetadata', 'Raw usageMetadata'],
    recent: ['近期结果', 'Recent outcomes'],
    recentFailure: ['最近错误', 'Last error'],
    recentHint: ['仅显示已记录的实际结果', 'Recorded outcomes only'],
    records: ['条记录', 'records'],
    refresh: ['刷新', 'Refresh'],
    reported: ['已回报', 'Reported'],
    requestDetail: ['客户端请求详情', 'Client request details'],
    requestId: ['请求 ID', 'Request ID'],
    requestLog: ['查看系统日志', 'Open system logs'],
    requests: ['请求', 'Requests'],
    requestScopeHint: [
        '包含本地拒绝；一次请求可包含多次账号调用',
        'Includes local rejections; a request can contain multiple calls',
    ],
    requestStatus: ['返回客户端', 'Returned to client'],
    reset: ['重置', 'Reset'],
    resume: ['恢复更新', 'Resume'],
    retried: ['发生重试', 'Retried'],
    retry: ['重试', 'Retry'],
    runtimeUnknown: ['运行状态未知', 'Runtime unknown'],
    safeKey: ['调用方标识（非完整密钥）', 'Caller identifier (not the full key)'],
    scope: ['统计口径', 'Scope'],
    search: ['搜索账号、模型或错误', 'Search account, model or error'],
    selectedAccountScope: ['已选账号：仅统计该账号的调用', 'Selected account: its calls only'],
    session_match: ['会话标识匹配', 'Session ID matched'],
    sessionIdentity: ['根据客户端会话 ID 识别', 'Identified by the client session ID'],
    snapshot: ['历史快照', 'History snapshot'],
    sort: ['排序', 'Sort'],
    source: ['状态来源', 'Status source'],
    standard: ['标准', 'Standard'],
    started: ['开始', 'Started'],
    status: ['状态', 'Status'],
    statusCode: ['状态码', 'Status code'],
    success: ['成功', 'Success'],
    successRate: ['成功率', 'Success rate'],
    termination: ['终止原因', 'Termination reason'],
    test: ['手动测试', 'Manual test'],
    testTag: ['测试', 'Test'],
    thought: ['思考 Token', 'Thought tokens'],
    thoughtsIncluded: ['输出包含思考 Token', 'Output includes thought tokens'],
    time: ['时间', 'Time'],
    timeout: ['超时', 'Timeout'],
    timezone: ['时区', 'Timezone'],
    title: ['请求监控', 'Request monitor'],
    tokenStructure: ['Token 结构', 'Token breakdown'],
    total: ['总 Token', 'Total tokens'],
    tps: ['生成 TPS', 'Generation TPS'],
    trend: ['查看趋势', 'Show trend'],
    trendEmpty: ['没有趋势数据', 'No trend data'],
    trendMetric: ['趋势指标', 'Trend metric'],
    ttft: ['首字时间', 'First text latency'],
    unassigned: ['未分配账号', 'Unassigned'],
    unattributed: ['历史归属未知', 'Unattributed history'],
    unclassified: ['来源未知', 'Unclassified'],
    unknown: ['未知', 'Unknown'],
    unknownCount: ['未知', 'Unknown'],
    unreported: ['未回报', 'Not reported'],
    updated: ['更新', 'Updated'],
    upstream: ['上游', 'Upstream'],
    usage: ['用量', 'Usage'],
    viewCalls: ['查看调用', 'View calls'],
    viewConversation: ['查看同一对话的请求', 'View requests in this conversation'],
    viewFailures: ['查看失败', 'View failures'],
    viewRequests: ['查看请求', 'View requests'],
    waiting: ['等待中', 'Waiting'],
};
export function monitorLabel(key, language = 'zh') {
    return labels[key]?.[language === 'en' ? 1 : 0] || key;
}
